In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\Krthicka\Downloads\Hotel.csv")
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-veg,-6755,4,87777,30-35

In [3]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
dtype: bool

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     str
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     str
 4   FoodPreference   11 non-null     str
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     str
dtypes: int64(5), str(4)
memory usage: 1.1 KB

In [5]:
df.drop_duplicates(inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-veg,-6755,4,87777,30-35

In [6]:
len(df)

10

In [7]:
index=np.array(list(range(0,len(df))))
df.set_index(index,inplace=True)
index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-veg,-6755,4,87777,30-35

In [9]:
df.drop(['Age_Group.1'],axis=1,inplace=True)
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-veg,-6755,4,87777

In [10]:
df.CustomerID.loc[df.CustomerID<0]=np.nan
df.Bill.loc[df.Bill<0]=np.nan
df.EstimatedSalary.loc[df.EstimatedSalary<0]=np.nan
df

C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\2080958306.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.CustomerID.loc[df.CustomerID<0]=np.nan
C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\2080958306.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.Bill.loc[df.Bill<0]=np.nan
C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\2080958306.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.EstimatedSalary.loc[df.EstimatedSalary<0]=np.nan

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-veg,-6755,4,87777

In [11]:
df['NoOfPax'].loc[(df['NoOfPax']<1) | (df['NoOfPax']>20)]=np.nan
df

C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\2129877948.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df['NoOfPax'].loc[(df['NoOfPax']<1) | (df['NoOfPax']>20)]=np.nan

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-veg,-6755,4,87777

In [12]:
df.Age_Group.unique()

<ArrowStringArray>
['20-25', '30-35', '25-30', '35+']
Length: 4, dtype: str

In [13]:
df.Hotel.unique()

<ArrowStringArray>
['Ibis', 'LemonTree', 'RedFox', 'Ibys']
Length: 4, dtype: str

In [14]:
df.Hotel.replace(['Ibys'],'Ibis',inplace=True)
df.FoodPreference.unique

C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\456600217.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.Hotel.replace(['Ibys'],'Ibis',inplace=True)

<bound method Series.unique of 0           veg
1       Non-Veg
2           Veg
3           Veg
4    Vegetarian
5       Non-Veg
6    Vegetarian
7           Veg
8       Non-Veg
9       non-veg
Name: FoodPreference, dtype: str>

In [15]:
df.FoodPreference.replace(['Vegetarian','veg'],'Veg',inplace=True)
df.FoodPreference.replace(['non-Veg'],'Non-Veg',inplace=True)

C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\3377581060.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.FoodPreference.replace(['Vegetarian','veg'],'Veg',inplace=True)
C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\3377581060.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.FoodPreference.replace(['non-Veg'],'Non-Veg',inplace=True)

0           veg
1       Non-Veg
2           Veg
3           Veg
4    Vegetarian
5       Non-Veg
6    Vegetarian
7           Veg
8       Non-Veg
9       non-veg
Name: FoodPreference, dtype: str

In [16]:
df.EstimatedSalary.fillna(round(df.EstimatedSalary.mean()),inplace=True)
df.NoOfPax.fillna(round(df.NoOfPax.median()),inplace=True)
df['Rating(1-5)'].fillna(round(df['Rating(1-5)'].median()), inplace=True)
df.Bill.fillna(round(df.Bill.mean()),inplace=True)
df

C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\3711388855.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.EstimatedSalary.fillna(round(df.EstimatedSalary.mean()),inplace=True)
C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\3711388855.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.NoOfPax.fillna(round(df.NoOfPax.median()),inplace=True)
C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\3711388855.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Rating(1-5)'].fillna(round(df['Rating(1-5)'].median()), inplace=True)
C:\Users\Krthicka\AppData\Local\Temp\ipykernel_960\3711388855.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.Bill.fillna(round(df.Bill.mean()),inplace=True)

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-veg,-6755,4,87777